spring:
  transaction:
    rollback-on-commit-failure: true
  security:
    useRedisRepo: true
    loginPath: /login
    ignoringAntMatchers:
      - /common/**
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tamboot_sample_db?useUnicode=true&characterEncoding=utf-8&&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
    username: root
    password: Aa123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  ignoreInterceptor: false
  throwVersionLockException: true
  snowFlake:
    machineId: 0
  configuration:
    mapUnderscoreToCamelCase: true
tamboot:
  job:
    refreshCron: 0 0/1 * * * ?
    threadCount: 5
  rocketmq:
    namesrv: 127.0.0.1:9876
    simpleProducer:
      group: simpleProducerGroup
    transactionProducer:
      group: transactionProducerGroup